services:
  service-nlp:
    build: ./service_nlp
    ports:
      - "8001:8001"
    restart: unless-stopped

  core-engine:
    build: ./core-engine
    ports:
      - "8002:8002"
    env_file:
      - .env
    restart: unless-stopped

  api-gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    environment:
      - NLP_SERVICE_URL=http://service-nlp:8001/analyze
      - URL_SERVICE_URL=http://core-engine:8002/analyze/links
    depends_on:
      - service-nlp
      - core-engine
    restart: unless-stopped
