name: Backend Quality Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Linting Tool
        run: pip install flake8
      - name: Run Lint
        run: flake8 api_gateway/ service_nlp/ --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Test with pytest
        run: python -m pytest tests/test_gateway.py